framework:
    mailer:
        envelope:
            sender: 'postmaster@nssmhttb.ovh'
            recipients: ['postmaster@nssmhttb.ovh']
        headers:
            from: 'Nassim <postmaster@nssmhttb.ovh>'
            to: 'postmaster@nssmhttb.ovh'
        dsn: '%env(MAILER_DSN)%'