name: Deploy

on: 
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/portfolio"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      env:
        APP_ENV: ${{ secrets.APP_ENV }}
        MAILER_DSN: ${{ secrets.MAILER_DSN }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: APP_ENV,MAILER_DSN
        script: |
          cd /var/www/portfolio
          echo ${{ secrets.APP_ENV }}
          echo "${{ secrets.APP_ENV }}"
          echo  "I am $APP_ENV"
          echo $APP_ENV
          ls