name: Deploy

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/portfolio"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/portfolio

          SYMFONY_ENV=prod composer install --no-dev --optimize-autoloader

          rm -rf .env 2> /dev/null
          rm -rf .env.local.php 2> /dev/null
          echo "${{ secrets.APP_ENV }}" >> .env
          echo "${{ secrets.APP_SECRET }}" >> .env
          echo "${{ secrets.DATABASE_URL }}" >> .env
          echo "${{ secrets.MAILER_DSN }}" >> .env
          
          composer dump-env prod
          
          php bin/console doctrine:database:create

          yarn install
          yarn build