name: Deploy

on: 
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/portfolio"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      # env:
      #   APP_ENV: ${{ secrets.APP_ENV }}
      #   MAILER_DSN: ${{ secrets.MAILER_DSN }}
      #   DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #   APP_SECRET: 
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/portfolio
          rm -rf .env
          echo "${{ secrets.APP_ENV }}" >> .env
          echo "${{ secrets.APP_SECRET }}" >> .env
          echo "${{ secrets.DATABASE_URL }}" >> .env
          echo "${{ secrets.MAILER_DSN }}" >> .env
          composer install --no-dev
          composer update --lock
          yarn install
          yarn build